# Generated by Django 4.2.3 on 2023-07-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_delete_profil_delete_statis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jumlah',
            field=models.IntegerField(blank=True, choices=[('Baru', 'Baru'), ('Lama', 'Lama')], default=0, null=True),
        ),
    ]
