# Generated by Django 4.2.3 on 2023-07-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_product_jumlah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='jumlah',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='jumlah (0)'),
        ),
    ]
