# Generated by Django 4.2.3 on 2023-07-24 02:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0007_alter_product_stok'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='banner_dua',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[800, 200], upload_to='gambar/banner', verbose_name='Gambar (575 x 200 pixel)'),
        ),
    ]
