# Generated by Django 4.2.3 on 2023-08-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='bukti_transfer',
            field=models.FileField(blank=True, null=True, upload_to='bukti_transfer/'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='metode_pembayaran',
            field=models.CharField(choices=[('cod', 'COD (Bayar di tempat)'), ('transfer', 'Transfer Bank')], default='cod', max_length=20),
        ),
    ]
