# Generated by Django 4.2.3 on 2023-08-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_transaksi_bukti_transfer_transaksi_metode_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='bukti_transfer',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
