# Generated by Django 4.2.3 on 2023-08-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_transaksi_bukti_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='bukti_transfer',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
