# Generated by Django 4.2.3 on 2023-08-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_transaksi_bukti_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='bukti_transfer',
            field=models.ImageField(null=True, upload_to='gambar/bukti', verbose_name='Gambar (475 x 880 pixel)'),
        ),
    ]
